import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";
import { ThemeProvider } from "@/components/ThemeProvider";
import { LayoutProvider } from "@/components/LayoutProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AuthProvider } from "@/contexts/AuthContext";
import GlobalLayout from "@/components/Layouts/GLobalLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
           <GlobalLayout>
             <AuthProvider>
        <ThemeProvider>
          
            <LayoutProvider>
              <TooltipProvider>{children}</TooltipProvider>
            </LayoutProvider>

            <Toaster />
         
        </ThemeProvider>
         </AuthProvider>
         </GlobalLayout>
         </Providers>
        
      </body>
    </html>
  );
}
